from redbaron import RedBaron

def condense(multi_line_string):
    """Condense a multiline string to one line using \n."""
    split_string = multi_line_string.split('\n')
    start_index = 1 if split_string[0] == '' else 0
    end_index = -1 if split_string[-1] == '' else -0
    return '\n'.join(split_string[start_index:end_index])

preamble_text = '''
# -*- coding: utf-8 -*-
# flake8:noqa
# isort:skip_file
# vim:et:ft=python:nowrap:sts=4:sw=4:ts=4
##############################################################################
# Note: Generated by soapfish.xsd2py at 2017-05-11 20:11:30.982888
#       Try to avoid editing it if you might need to regenerate it.
##############################################################################
'''

import_line = '''
from soapfish import xsd
'''


x = RedBaron(condense(preamble_text))
x.append()
